name: test

on:
  schedule:
    - cron: '0 * * * *'
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: sh test.sh
        env:
          SECRET: ${{ secrets.TEST }}
